export { default as Home } from './home';
export { default as Dashboard } from './admin/dashboard';
export { default as SignIn } from './auth/signin';
export { default as SignUp } from './auth/signup';
export { default as FeaturedProducts } from './featured';
export { default as RecommendedProducts } from './recommended';
export { default as Search } from './search';
export { default as Shop } from './shop';
export { default as ViewProduct } from './view_product';